#ifndef __ONEM2M_TYPES_H__
#define __ONEM2M_TYPES_H__

#include <stdbool.h>

typedef enum {
	IN_CSE = 1,
	MN_CSE = 2,
	ASN_CSE = 3
} CSEType;

typedef enum {
    RSC_ACCEPTED									= 1000,
	RSC_ACCEPTED_NONBLOCKING_REQUEST_SYNCH			= 1001,
	RSC_ACCEPTED_NONBLOCKING_REQUEST_ASYNCH			= 1002,
	RSC_OK											= 2000,
	RSC_CREATED 									= 2001,
	RSC_DELETED 									= 2002,
	RSC_UPDATED										= 2004,
	RSC_BAD_REQUEST									= 4000,
	RSC_RELEASE_VERSION_NOT_SUPPORTED				= 4001,
	RSC_NOT_FOUND 									= 4004,
	RSC_OPERATION_NOT_ALLOWED						= 4005,
	RSC_REQUEST_TIMEOUT 							= 4008,
	RSC_UNSUPPORTED_MEDIATYPE						= 4015,
	RSC_SUBSCRIPTION_CREATOR_HAS_NO_PRIVILEGE		= 4101,
	RSC_CONTENTS_UNACCEPTABLE						= 4102,
	RSC_ORIGINATOR_HAS_NO_PRIVILEGE					= 4103,
	RSC_GROUP_REQUEST_IDENTIFIER_EXISTS				= 4104,
	RSC_CONFLICT									= 4105,
	RSC_ORIGINATOR_HAS_NOT_REGISTERED				= 4106,
	RSC_SECURIRT_ASSOCIATION_REQUIRED				= 4107,
	RSC_INVALID_CHILD_RESOURCETYPE					= 4108,
	RSC_NO_MEMBERS									= 4109,
	RSC_GROUPMEMBER_TYPE_INCONSISTENT				= 4110,
	RSC_ESPRIM_UNSUPPORTED_OPTION					= 4111,
 	RSC_ESPRIM_UNKNOWN_KEY_ID						= 4112,
	RSC_ESPRIM_UNKNOWN_ORIG_RAND_ID					= 4113,
	RSC_ESPRIM_UNKNOWN_RECV_RAND_ID					= 4114,
 	RSC_ESPRIM_BAD_MAC								= 4115,
	RSC_ESPRIM_IMPERSONATION_ERROR					= 4116,
	RSC_ORIGINATOR_HAS_ALREADY_REGISTERD			= 4117,
	RSC_ONTOLOGY_NOT_AVAILABLE						= 4118,
	RSC_LINKED_SEMANTICS_NOT_AVAILABLE				= 4119,
	RSC_INVALID_SEMANTICS							= 4120,
	RSC_MASHUP_MEMBER_NOT_FOUND						= 4121,
	RSC_INVALID_TRIGGER_PURPOSE						= 4122,
	RSC_ILLEGAL_TRANSACTION_STATE_TRANSITION_ATTEMPTED = 4123,
	RSC_BLOCKING_SUBSCRIPTION_ALREADY_EXISTS		= 4124,
	RSC_SPECIALIZATION_SCHEMA_NOT_FOUND				= 4125,
	RSC_APP_RULE_VALIDATION_FAILED					= 4126,
	RSC_OPERATION_DENIED_BY_REMOTE_ENTITY			= 4127,
	RSC_SERVICE_SUBSCRIPTION_NOT_ESTABLISHED		= 4128,
	RSC_INVALID_SPARQL_QUERY						= 4143,
	RSC_INTERNAL_SERVER_ERROR						= 5000,
	RSC_NOT_IMPLEMENTED								= 5001,
	RSC_TARGET_NOT_REACHABLE						= 5103,
	RSC_RECEIVER_HAS_NO_PRIVILEGES 					= 5105,
	RSC_ALREADY_EXISTS								= 5106,
	RSC_REMOTE_ENTIRT_NOT_REACHABLE					= 5107,
	RSC_TARGET_NOT_SUBSCRIBABLE						= 5203,
	RSC_SUBSCRIPTION_VERIFICATION_INITIATION_FAILED	= 5204,
	RSC_SUBSCRIPTION_HOST_HAS_NO_PRIVILEGE			= 5205,
	RSC_NON_BLOCKING_SYNCH_REQUEST_NOT_SUPPORTED	= 5206,
	RSC_NOT_ACCEPTABLE 								= 5207,
	RSC_DISCOVERY_DENIED_BY_IPE						= 5208,
	RSC_GROUP_MEMBERS_NOT_RESPONDED					= 5209,
	RSC_CROSS_RESOURCE_OPERATION_FAILURE			= 5221,
	RSC_MAX_NUMBER_OF_MEMBER_EXCEEDED				= 6010,
	RSC_INVALID_ARGUMENTS							= 6023,
	RSC_INSUFFICIENT_ARGUMENTS						= 6024,
}ResponseStatusCode;


typedef enum {
	RT_MIXED = 0,
	RT_ACP = 1,
	RT_AE = 2,
	RT_CNT = 3,
	RT_CIN = 4,
	RT_CSE = 5,
	RT_GRP = 9,
	RT_MGMTOBJ = 13,
	RT_NOD = 14,
	RT_PCH = 15,
	RT_CSR = 16,
	RT_REQ = 17,
	RT_SUB = 23,
	RT_SMD = 24,
	RT_FCNT = 28,
	RT_TS = 29,
	RT_TSI = 30,
	RT_CRS = 48,
	RT_FCI = 58,
	RT_TSB = 60,
	RT_ACTR = 63,
} ResourceType;

typedef enum {
	RCN_NOTHING									= 0,
	RCN_ATTRIBUTES 								= 1,
	RCN_HIERARCHICAL_ADDRESS					= 2,
	RCN_HIERARCHICAL_ADDRESS_ATTRIBUTES			= 3,
	RCN_ATTRIBUTES_AND_CHILD_RESOURCES			= 4	,
	RCN_ATTRIBUTES_AND_CHILD_RESOURCE_REFERENCES= 5,
	RCN_CHILD_RESOURCE_REFERENCES				= 6,
	RCN_ORIGINAL_RESOURCE 						= 7,
	RCN_CHILD_RESOURCES							= 8,
	RCN_MODIFIED_ATTRIBUTES						= 9,
	RCN_SEMANTIC_CONTENT						= 10,
	RCN_DISCOVERY_RESULT_REFERENCES				= 11,
	RCN_PERMISSIONS								= 12
} ResultContentType;

typedef enum {
	DRT_STRUCTURED = 1,
	DRT_UNSTRUCTURED = 2,
} desIdResType;

typedef enum {
	NCT_ALL_ATTRIBUTES = 1,
	NCT_MODIFIED_ATTRIBUTES = 2,
	NCT_RESOURCE_ID = 3,
	NCT_TRIGGER_PAYLOAD = 4,
	NCT_TIMESERIES_NOTIFICATION = 5,
} notificationContentType;

typedef enum {
	CSY_ABANDON_MEMBER = 1,
	CSY_ABANDON_GROUP = 2,
	CSY_SET_MIXED = 3
} ConsistencyStrategy;

typedef enum {
	NET_NONE = 0,
	NET_UPDATE_OF_RESOURCE = 1,
	NET_DELETE_OF_RESOURCE = 2,
	NET_CREATE_OF_DIRECT_CHILD_RESOURCE = 3,
	NET_DELETE_OF_DIRECT_CHILD_RESOURCE = 4,
	NET_RETRIEVE_OF_CONTAINER_RESOURCE_WITH_NO_CHILD_RESOURCE = 5,
	NET_TRIGGER_RECIEVED_FOR_AE_RESOURCE = 6,
	NET_BLOCKING_UPDATE = 7,
	NET_REPORT_ON_MISSING_DATA_POINTS = 8
} NotificationEventType;

#endif