#ifndef __ONEM2M_TYPES_H__
#define __ONEM2M_TYPES_H__

#include <stdbool.h>

typedef enum
{
	IN_CSE = 1,
	MN_CSE = 2,
	ASN_CSE = 3
} CSEType;

typedef enum
{
	PROT_HTTP = 1,
	PROT_MQTT,
	PROT_COAP = 3,
	PROT_COAPS = 4
} Protocol;

typedef enum
{
	OP_NONE = 0,
	OP_CREATE = 1,
	OP_RETRIEVE = 2,
	OP_UPDATE = 3,
	OP_DELETE = 4,
	OP_NOTIFY = 5,
	OP_DISCOVERY = 6,
	OP_VIEWER = 1000,
	OP_OPTIONS,
	OP_FORWARDING,
	OP_UPPERTESTER
} Operation;

typedef enum
{
	ACOP_CREATE = 1,
	ACOP_RETRIEVE = 2,
	ACOP_UPDATE = 4,
	ACOP_DELETE = 8,
	ACOP_NOTIFY = 16,
	ACOP_DISCOVERY = 32
} ACOP;

typedef enum
{
	RVI_NONE,
	RVI_1,
	RVI_2,
	RVI_2a,
	RVI_3,
	RVI_4,
	RVI_5,
} RVI;

typedef enum
{
	CS_PARTIAL_CONTENT = 1,
	CS_FULL_CONTENT = 2
} ContentStatus;

typedef enum
{
	FU_DISCOVERY = 1,
	FU_CONDITIONAL_OPERATION = 2, // DEFAULT
	FU_IPE_ON_DEMAND_DISCOVERY = 3,
	FU_DISCOVERY_BASED_OPERATION = 4
} FilterUsage;

typedef enum
{
	FO_AND = 1, // DEFAULT
	FO_OR = 2,
	FO_XOR = 3
} FilterOperation;

typedef enum
{
	CSE_RELATIVE = 1,	  // CSEBase relative  starts with ''
	SP_RELATIVE = 2,	  // SP relative starts with '/'
	ABSOLUTE = 3,		  // absolute starts with '//'
	PROTOCOL_BINDING = 4, // protocol binding starts with 'http://, coap://, mqtt://'
} ResourceAddressingType;

typedef enum
{
	RSC_ACCEPTED = 1000,
	RSC_ACCEPTED_NONBLOCKING_REQUEST_SYNCH = 1001,
	RSC_ACCEPTED_NONBLOCKING_REQUEST_ASYNCH = 1002,
	RSC_OK = 2000,
	RSC_CREATED = 2001,
	RSC_DELETED = 2002,
	RSC_UPDATED = 2004,
	RSC_BAD_REQUEST = 4000,
	RSC_RELEASE_VERSION_NOT_SUPPORTED = 4001,
	RSC_NOT_FOUND = 4004,
	RSC_OPERATION_NOT_ALLOWED = 4005,
	RSC_REQUEST_TIMEOUT = 4008,
	RSC_UNSUPPORTED_MEDIATYPE = 4015,
	RSC_SUBSCRIPTION_CREATOR_HAS_NO_PRIVILEGE = 4101,
	RSC_CONTENTS_UNACCEPTABLE = 4102,
	RSC_ORIGINATOR_HAS_NO_PRIVILEGE = 4103,
	RSC_GROUP_REQUEST_IDENTIFIER_EXISTS = 4104,
	RSC_CONFLICT = 4105,
	RSC_ORIGINATOR_HAS_NOT_REGISTERED = 4106,
	RSC_SECURITY_ASSOCIATION_REQUIRED = 4107,
	RSC_INVALID_CHILD_RESOURCETYPE = 4108,
	RSC_NO_MEMBERS = 4109,
	RSC_GROUPMEMBER_TYPE_INCONSISTENT = 4110,
	RSC_ESPRIM_UNSUPPORTED_OPTION = 4111,
	RSC_ESPRIM_UNKNOWN_KEY_ID = 4112,
	RSC_ESPRIM_UNKNOWN_ORIG_RAND_ID = 4113,
	RSC_ESPRIM_UNKNOWN_RECV_RAND_ID = 4114,
	RSC_ESPRIM_BAD_MAC = 4115,
	RSC_ESPRIM_IMPERSONATION_ERROR = 4116,
	RSC_ORIGINATOR_HAS_ALREADY_REGISTERD = 4117,
	RSC_ONTOLOGY_NOT_AVAILABLE = 4118,
	RSC_LINKED_SEMANTICS_NOT_AVAILABLE = 4119,
	RSC_INVALID_SEMANTICS = 4120,
	RSC_MASHUP_MEMBER_NOT_FOUND = 4121,
	RSC_INVALID_TRIGGER_PURPOSE = 4122,
	RSC_ILLEGAL_TRANSACTION_STATE_TRANSITION_ATTEMPTED = 4123,
	RSC_BLOCKING_SUBSCRIPTION_ALREADY_EXISTS = 4124,
	RSC_SPECIALIZATION_SCHEMA_NOT_FOUND = 4125,
	RSC_APP_RULE_VALIDATION_FAILED = 4126,
	RSC_OPERATION_DENIED_BY_REMOTE_ENTITY = 4127,
	RSC_SERVICE_SUBSCRIPTION_NOT_ESTABLISHED = 4128,
	RSC_ONTOLOGY_MAPPING_ALGORITHM_NOT_AVAILABLE = 4130,
	RSC_ONTOLOGY_MAPPING_POLICY_NOT_MATCHED = 4131,
	RSC_ONTOLOGY_MAPPING_NOT_AVAILABLE = 4132,
	RSC_BAD_FACT_INPUTS_FOR_REASONING = 4133,
	RSC_BAD_RULE_INPUTS_FOR_REASONING = 4134,
	RSC_DISCOVERY_LIMIT_EXCEEDED = 4135,
	RSC_PRIMITIVE_PROFILE_NOT_ACCESSIBLE = 4136,
	RSC_PRIMITIVE_PROFILE_BAD_REQUEST = 4137,
	RSC_UNAUTHORIZED_USER = 4138,
	RSC_SERVICE_SUBSCRIPTION_NOT_ACTIVE = 4139,
	RSC_SOFTWARE_CAMPAIGN_CONFLICT = 4140,
	RSC_INVALID_SPARQL_QUERY = 4143,
	RSC_INTERNAL_SERVER_ERROR = 5000,
	RSC_NOT_IMPLEMENTED = 5001,
	RSC_TARGET_NOT_REACHABLE = 5103,
	RSC_RECEIVER_HAS_NO_PRIVILEGES = 5105,
	RSC_ALREADY_EXISTS = 5106,
	RSC_REMOTE_ENTITY_NOT_REACHABLE = 5107,
	RSC_TARGET_NOT_SUBSCRIBABLE = 5203,
	RSC_SUBSCRIPTION_VERIFICATION_INITIATION_FAILED = 5204,
	RSC_SUBSCRIPTION_HOST_HAS_NO_PRIVILEGE = 5205,
	RSC_NON_BLOCKING_SYNCH_REQUEST_NOT_SUPPORTED = 5206,
	RSC_NOT_ACCEPTABLE = 5207,
	RSC_DISCOVERY_DENIED_BY_IPE = 5208,
	RSC_GROUP_MEMBERS_NOT_RESPONDED = 5209,
	RSC_ESPRIM_DECRYPTION_ERROR = 5210,
	RSC_ESPRIM_ENCRYPTION_ERROR = 5211,
	RSC_SPARQL_UPDATE_ERROR = 5212,
	RSC_TARGET_HAS_NO_SESSION_CAPABILITY = 5214,
	RSC_SESSION_IS_ONLINE = 5215,
	RSC_JOIN_MULTICAST_GROUP_FAILED = 5216,
	RSC_LEAVE_MULTICAST_GROUP_FAILED = 5217,
	RSC_TRIGGERING_DISABLED_FOR_RECIPIENT = 5218,
	RSC_UNABLE_TO_REPLACE_GROUP_MEMBER = 5219,
	RSC_UNABLE_TO_RECALL_REQUEST = 5220,
	RSC_CROSS_RESOURCE_OPERATION_FAILURE = 5221,
	RSC_TRANSACTION_PROCESSING_IS_INCOMPLETE = 5222,
	RSC_ONTOLOGY_MAPPING_ALGORITHM_FAILED = 5230,
	RSC_ONTOLOGY_CONVERSION_FAILED = 5231,
	RSC_REASONING_PROCESSING_FAILED = 5232,
	RSC_EXTERNAL_OBJECT_NOT_REACHABLE = 6003,
	RSC_EXTERNAL_OBJECT_NOT_FOUND = 6005,
	RSC_MAX_NUMBER_OF_MEMBER_EXCEEDED = 6010,
	RSC_MGMT_SESSION_CANNOT_BE_ESTABLISHED = 6020,
	RSC_MGMT_SESSION_ESTABLISHMENT_TIMEOUT = 6021,
	RSC_INVALID_CMDTYPE = 6022,
	RSC_INVALID_ARGUMENTS = 6023,
	RSC_INSUFFICIENT_ARGUMENTS = 6024,
	RSC_MGMT_CONVERSION_ERROR = 6025,
	RSC_MGMT_CANCELLATION_FAILED = 6026,
	RSC_ALREADY_COMPLETE = 6028,
	RSC_MGMT_COMMAND_NOT_CANCELLABLE = 6029,
	RSC_EXTERNAL_OBJECT_NOT_REACHABLE_BEFORE_RQET_TIMEOUT = 6030,
	RSC_EXTERNAL_OBJECT_NOT_REACHABLE_BEFORE_OET_TIMEOUT = 6031,
	RSC_NETWORK_QOS_CONFIG_ERROR = 6033,
	RSC_REQUESTED_ACTIVITY_PATTERN_NOT_PERMITTED = 6034,
} ResponseStatusCode;

typedef enum
{
	RT_MIXED = 0,
	RT_ACP = 1,		 // Access Control Policy
	RT_AE = 2,		 // Application Entity
	RT_CNT = 3,		 // Container
	RT_CIN = 4,		 // Content Instance
	RT_CSE = 5,		 // Common Services Entity Base
	RT_GRP = 9,		 // Group
	RT_MGMTOBJ = 13, // Management Object
	RT_NOD = 14,	 // Node
	RT_PCH = 15,	 // Polling Channel
	RT_CSR = 16,	 // Remote CSE
	RT_REQ = 17,	 // Request
	RT_SUB = 23,	 // Subscription
	RT_SMD = 24,	 // Semantic Descriptor
	RT_FCNT = 28,	 // FlexContainer
	RT_TS = 29,		 // Time Series
	RT_TSI = 30,	 // Time Series Instance
	RT_CRS = 48,
	RT_FCI = 58,
	RT_TSB = 60,
	RT_ACTR = 63,
	RT_ACPA = 10001,
	RT_AEA = 10002,
	RT_CNTA = 10003,
	RT_CINA = 10004,
	RT_CBA = 10005,
	RT_GRPA = 10009,
} ResourceType;

typedef enum
{
	RCN_NOTHING = 0,
	RCN_ATTRIBUTES = 1,
	RCN_HIERARCHICAL_ADDRESS = 2,
	RCN_HIERARCHICAL_ADDRESS_ATTRIBUTES = 3,
	RCN_ATTRIBUTES_AND_CHILD_RESOURCES = 4,
	RCN_ATTRIBUTES_AND_CHILD_RESOURCE_REFERENCES = 5,
	RCN_CHILD_RESOURCE_REFERENCES = 6,
	RCN_ORIGINAL_RESOURCE = 7,
	RCN_CHILD_RESOURCES = 8,
	RCN_MODIFIED_ATTRIBUTES = 9,
	RCN_SEMANTIC_CONTENT = 10,
	RCN_DISCOVERY_RESULT_REFERENCES = 11,
	RCN_PERMISSIONS = 12
} ResultContentType;

typedef enum
{
	DRT_STRUCTURED = 1,
	DRT_UNSTRUCTURED = 2,
} desIdResType;

typedef enum
{
	NCT_ALL_ATTRIBUTES = 1,
	NCT_MODIFIED_ATTRIBUTES = 2,
	NCT_RESOURCE_ID = 3,
	NCT_TRIGGER_PAYLOAD = 4,
	NCT_TIMESERIES_NOTIFICATION = 5,
} notificationContentType;

typedef enum
{
	CSY_ABANDON_MEMBER = 1,
	CSY_ABANDON_GROUP = 2,
	CSY_SET_MIXED = 3
} ConsistencyStrategy;

typedef enum
{
	NET_NONE = 0,
	NET_UPDATE_OF_RESOURCE = 1,
	NET_DELETE_OF_RESOURCE = 2,
	NET_CREATE_OF_DIRECT_CHILD_RESOURCE = 3,
	NET_DELETE_OF_DIRECT_CHILD_RESOURCE = 4,
	NET_RETRIEVE_OF_CONTAINER_RESOURCE_WITH_NO_CHILD_RESOURCE = 5,
	NET_TRIGGER_RECIEVED_FOR_AE_RESOURCE = 6,
	NET_BLOCKING_UPDATE = 7,
	NET_REPORT_ON_MISSING_DATA_POINTS = 8
} NotificationEventType;

typedef enum
{
	AST_UNI_DIRECTIONAL = 1,
	AST_BI_DIRECTIONAL = 2,
} AnnounceSyncType;

#endif